name: Unit tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: |
          poetry install 

      - name: Run tests with pytest
        run: poetry run pytest